script:
- if [[ "$TRAVIS_TAG" != "" ]]; then return; fi
- git config --global credential.helper store
- echo "https://$GitHub_auth_token:x-oauth-basic@github.com" >$HOME/.git-credentials
- git config --global user.email "nobody@no.mail"
- git config --global user.name "Travis CI"
- git tag -f same
- git tag new-$TRAVIS_JOB_NUMBER
- git push -f --tags

before_deploy: |-
  echo test >a5.txt
  echo test >a5_ół.txt
  echo tag = $TRAVIS_TAG
  echo Filenames before
  ls *.txt
  if [[ "$TRAVIS_TAG" == "same" ]]; then
    curl -H "Authorization: token $GitHub_auth_token" \
      https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases/tags/$TRAVIS_TAG | \
      grep '"name"'
  fi

after_deploy: |-
  echo Filenames after
  curl -H "Authorization: token $GitHub_auth_token" \
    https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases/tags/$TRAVIS_TAG | \
    grep '"name"'

deploy:
- provider: releases
  api_key: $GitHub_auth_token
  name: $TRAVIS_TAG
  file_glob: true
  file: ./*.txt
  skip_cleanup: true
  overwrite: true
  on:
      condition: "${#GitHub_auth_token} != 0"
      tags: true