script: |-
  if [[ "$TRAVIS_TAG" == "" ]]; then
    git config --global credential.helper store
    echo "https://$GitHub_auth_token:x-oauth-basic@github.com" >$HOME/.git-credentials
    git config --global user.email "nobody@no.mail"
    git config --global user.name "Travis CI"
    git tag -f same
    git tag new-$TRAVIS_JOB_NUMBER
    git push -f --tags
  fi

before_deploy: |-
  echo tag = $TRAVIS_TAG
  echo test >a5.txt
  echo test >a5_ół.txt
  ls *.txt
  curl -H "Authorization: token $GitHub_auth_token" https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases

deploy:
- provider: releases
  api_key: $GitHub_auth_token
  file_glob: true
  file: ./*.txt
  skip_cleanup: true
  overwrite: true
  on:
      condition: "${#GitHub_auth_token} != 0"
      tags: true